config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :boards
  resources :comments
  get '/home' => 'users#home',as: 'home'
  get '/about' => 'users#about',as: 'about'
  root 'users#index'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
	belongs_to :user
	has_many :comments,depandent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :board
end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :boards,dependent: :destroy
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
   enum sex: { man: 1, woman: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:sex,:birth_date])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
  end

  def show
  end
  def new
  	board = BOard.new
  end
  def create
  	
  end
  def update
  	
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end
  def new
  	
  end
  def create
  	
  end
  def update
  	
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def follow
  current_user.follow(params[:id])
  redirect_to root_path
end

def unfollow
  current_user.unfollow(params[:id])
  redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
  	
  end
  def about
  	
  end
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end
    def update
   @user = User.find(params[:id])
   @user.update(user_params)
      if @user.save
           redirect_to user_path(@user)
      else 
           render 'edit'
      end
 end

  private
  def user_params
  	params.require(:user).permit(:name, :birth_date, :sex)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<h1>Board#index</h1>
<p>Find me in app/views/board/index.html.erb</p>

app/views/boards/show.html.erb
<h1>Board#show</h1>
<p>Find me in app/views/board/show.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comment#index</h1>
<p>Find me in app/views/comment/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mozipa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
  <nav>
      
       <% if user_signed_in? %>
    <ul class="nav nav-tabs pull-right ">
            <li role="presentation"><%= link_to 'Home', user_path(current_user.id) %></li>
            <li role="presentation"><%= link_to 'Users', users_path %></li>
            <li role="presentation"><%= link_to 'Boards' , boards_path %></li>
            <li role="presentation"><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
        <ul class="nav nav-tabs pull-right">
            <li role="presentation"><%= link_to 'Home', home_path %></li>
            <li role="presentation"><%= link_to 'About', about_path %></li>
            <li role="presentation"><%= link_to 'sign up', new_user_registration_path %></li>
            <li role="presentation"><%= link_to 'login', new_user_session_path %></li>
            </ul>
            <% end %>
  </nav>
</header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<% if user_signed_in? %>
  <h1>ユーザー一覧画面</h1>
  <% @users.each do |user| %>
    <p>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>